type Products = {
  id: number;
  name: string;
  slug: string;
  category: string;
  image: string;
  isFeatured: boolean;
  price: number;
  description: string;
}[];

export const data: Products = [
  {
    id: 1,
    name: 'Free Shirt',
    slug: 'free-shirt-1',
    category: 'Shirts',
    image: 'shirt1.jpg',
    isFeatured: false,
    price: 70,
    description: 'Full sleeve Shirt',
  },
  {
    id: 2,
    name: 'Free Shirt',
    slug: 'free-shirt-2',
    category: 'Shirts',
    image: 'shirt2.jpg',
    isFeatured: false,
    price: 70,
    description: 'Full sleeve Shirt',
  },
  {
    id: 3,
    name: 'Free Shirt',
    slug: 'free-shirt-3',
    category: 'Shirts',
    image: 'shirt3.jpg',
    isFeatured: true,
    price: 70,
    description: 'Full sleeve Shirt',
  },
  {
    id: 4,
    name: 'Fit Pants',
    slug: 'fit-pants-4',
    category: 'Pants',
    image: 'pants1.jpg',
    isFeatured: true,
    price: 95,
    description: 'Jeans Pant',
  },
  {
    id: 5,
    name: 'Fit Pants',
    slug: 'fit-pants-5',
    category: 'Pants',
    image: 'pants2.jpg',
    isFeatured: false,
    price: 95,
    description: 'Jeans Pant',
  },
  {
    id: 6,
    name: 'Fit Pants',
    slug: 'fit-pants-6',
    category: 'Pants',
    image: 'pants3.jpg',
    isFeatured: false,
    price: 95,
    description: 'Jeans Pant',
  },
  {
    id: 7,
    name: 'Free Shirt ss',
    slug: 'free-shirt-3',
    category: 'Shirts',
    image: 'shirt3.jpg',
    isFeatured: false,
    price: 70,
    description: 'Full sleeve Shirt',
  },

  {
    id: 8,
    name: 'A-monochromatic-shirt',
    slug: 'a-monochromatic-shirt-and-background',
    category: 'Shirts',
    image: 'a-monochromatic-shirt-and-background.jpg',
    isFeatured: false,
    price: 50,
    description: 'Half sleeve orange Shirt',
  },

  {
    id: 9,
    name: 'Black-mi-band-smartwatch',
    slug: 'black-mi-band-smartwatch',
    category: 'Watch',
    image: 'black-mi-band-smartwatch.jpg',
    isFeatured: false,
    price: 90,
    description: 'A Smartwatch',
  },

  {
    id: 10,
    name: 'Shoulder-bag',
    slug: 'black-over-the-shoulder-bag',
    category: 'Bag',
    image: 'black-over-the-shoulder-bag.jpg',
    isFeatured: true,
    price: 50,
    description: 'black-over-the-shoulder-bag',
  },

  {
    id: 11,
    name: 'Black-sneakers',
    slug: 'black-sneakers-with-white-sole',
    category: 'Shoes',
    image: 'black-sneakers-with-white-sole.jpg',
    isFeatured: false,
    price: 40,
    description: 'black-sneakers-with-white-sole',
  },
  {
    id: 12,
    name: 'Black-white-wrist-watches',
    slug: 'black-white-wrist-watches',
    category: 'Watch',
    image: 'black-white-wrist-watches.jpg',
    isFeatured: false,
    price: 50,
    description: 'black-white-wrist-watches',
  },

  {
    id: 13,
    name: 'A blue-t-shirt',
    slug: 'blue-t-shirt',
    category: 'Shirts',
    image: 'blue-t-shirt.jpg',
    isFeatured: false,
    price: 50,
    description: 'blue-t-shirt',
  },
  {
    id: 14,
    name: 'Boho-bangle-bracelet',
    slug: 'boho-bangle-bracelet',
    category: 'Cosmetics',
    image: 'boho-bangle-bracelet.jpg',
    isFeatured: false,
    price: 5,
    description: 'boho-bangle-bracelet',
  },
  {
    id: 15,
    name: 'Bright-red-purse',
    slug: 'bright-red-purse-with-gold',
    category: 'Bag',
    image: 'bright-red-purse-with-gold.jpg',
    isFeatured: false,
    price: 50,
    description: 'bright-red-purse-with-gold',
  },

  {
    id: 16,
    name: 'Brown-purse',
    slug: 'brown-purse-with-shoulder-strap',
    category: 'Bag',
    image: 'brown-purse-with-shoulder-strap.jpg',
    isFeatured: false,
    price: 50,
    description: 'brown-purse-with-shoulder-strap',
  },
  {
    id: 17,
    name: 'Buddha-bracelet',
    slug: 'buddha-bracelet-for-men',
    category: 'Cosmetics',
    image: 'buddha-bracelet-for-men.jpg',
    isFeatured: false,
    price: 50,
    description: 'buddha-bracelet-for-men',
  },

  {
    id: 18,
    name: 'Camera-',
    slug: 'camera-with-product-on-table',
    category: 'Accessories',
    image: 'camera-with-product-on-table.jpg',
    isFeatured: true,
    price: 250,
    description: 'camera-with-product-on-table',
  },
  {
    id: 19,
    name: 'Chakra-bracelet',
    slug: 'chakra-bracelet-product-shot',
    category: 'Cosmetics',
    image: 'chakra-bracelet-product-shot.jpg',
    isFeatured: false,
    price: 50,
    description: 'chakra-bracelet-product-shot',
  },
  {
    id: 20,
    name: 'Coffee-product',
    slug: 'coffee-product-photo',
    category: 'Accessories',
    image: 'coffee-product-photo.jpg',
    isFeatured: true,
    price: 40,
    description: 'coffee-product-photo',
  },

  {
    id: 21,
    name: 'Geometric-socks',
    slug: 'color-geometric-socks',
    category: 'Socks',
    image: 'color-geometric-socks.jpg',
    isFeatured: false,
    price: 50,
    description: 'color-geometric-socks',
  },
  {
    id: 22,
    name: 'Iphone-case-blue-green',
    slug: 'cool-painted-iphone-case-blue-green',
    category: 'Accessories',
    image: 'cool-painted-iphone-case-blue-green.jpg',
    isFeatured: false,
    price: 50,
    description: 'cool-painted-iphone-case-blue-green',
  },

  {
    id: 23,
    name: 'Gold-necklace',
    slug: 'dainty-gold-necklace',
    category: 'Cosmetics',
    image: 'dainty-gold-necklace.jpg',
    isFeatured: false,
    price: 46,
    description: 'dainty-gold-necklace',
  },
  {
    id: 24,
    name: 'DIY-beard-balm',
    slug: 'DIY-beard-balm',
    category: 'Cosmetics',
    image: 'DIY-beard-balm.jpg',
    isFeatured: true,
    price: 50,
    description: 'DIY-beard-balm',
  },
  {
    id: 25,
    name: 'DIY-beard-oil',
    slug: 'DIY-beard-oil',
    category: 'Cosmetics',
    image: 'DIY-beard-oil.jpg',
    isFeatured: false,
    price: 50,
    description: 'DIY-beard-oil',
  },

  {
    id: 26,
    name: 'DIY-beard-oil-bottles',
    slug: 'DIY-beard-oil-bottles',
    category: 'Cosmetics',
    image: 'DIY-beard-oil-bottles.jpg',
    isFeatured: false,
    price: 50,
    description: 'DIY-beard-oil-bottles',
  },
  {
    id: 27,
    name: 'DIY-lip-balm',
    slug: 'DIY-lip-balm',
    category: 'Cosmetics',
    image: 'DIY-lip-balm.jpg',
    isFeatured: false,
    price: 50,
    description: 'DIY-lip-balm',
  },

  {
    id: 28,
    name: 'Elephant-earrings',
    slug: 'elephant-earrings',
    category: 'Cosmetics',
    image: 'elephant-earrings.jpg',
    isFeatured: false,
    price: 10,
    description: 'elephant-earrings',
  },
  {
    id: 29,
    name: 'Cat-socks',
    slug: 'feet-pose-in-cat-socks',
    category: 'Socks',
    image: 'feet-pose-in-cat-socks.jpg',
    isFeatured: false,
    price: 50,
    description: 'feet-pose-in-cat-socks',
  },
  {
    id: 30,
    name: 'Galaxy-earrings',
    slug: 'galaxy-earrings',
    category: 'Cosmetics',
    image: 'galaxy-earrings.jpg',
    isFeatured: false,
    price: 14,
    description: 'galaxy-earrings',
  },

  {
    id: 31,
    name: 'Geometric-socks',
    slug: 'geometric-socks',
    category: 'Socks',
    image: 'geometric-socks.jpg',
    isFeatured: false,
    price: 50,
    description: 'geometric-socks',
  },
  {
    id: 32,
    name: 'Iphone-case',
    slug: 'glittery-iphone-case',
    category: 'Accessories',
    image: 'glittery-iphone-case.jpg',
    isFeatured: false,
    price: 10,
    description: 'glittery-iphone-case',
  },

  {
    id: 33,
    name: 'Iphone-7-case',
    slug: 'gold-silver-iphone-7-case',
    category: 'Accessories',
    image: 'gold-silver-iphone-7-case.jpg',
    isFeatured: false,
    price: 50,
    description: 'gold-silver-iphone-7-case',
  },
  {
    id: 34,
    name: 'Black-fashion-backpack',
    slug: 'gold-zipper-on-black-fashion-backpack',
    category: 'Bag',
    image: 'gold-zipper-on-black-fashion-backpack.jpg',
    isFeatured: true,
    price: 50,
    description: 'gold-zipper-on-black-fashion-backpack',
  },
  {
    id: 35,
    name: 'A grey-t-shirt',
    slug: 'grey-t-shirt',
    category: 'Shirts',
    image: 'grey-t-shirt.jpg',
    isFeatured: false,
    price: 50,
    description: 'Half sleeve grey-t-shirt',
  },

  {
    id: 36,
    name: 'Stripe-socks',
    slug: 'grey-and-white-stripe-socks',
    category: 'Socks',
    image: 'grey-and-white-stripe-socks.jpg',
    isFeatured: false,
    price: 50,
    description: 'grey-and-white-stripe-socks',
  },
  {
    id: 37,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },

  {
    id: 38,
    name: 'iphone-7-glitter-case',
    slug: 'iphone-7-glitter-case-front-back',
    category: 'Accessories',
    image: 'iphone-7-glitter-case-front-back.jpg',
    isFeatured: false,
    price: 50,
    description: 'iphone-7-glitter-case-front-back',
  },
  {
    id: 39,
    name: 'Facemask',
    slug: 'ajar-of-activated-charcoal-facemask',
    category: 'Cosmetics',
    image: 'jar-of-activated-charcoal-facemask.jpg',
    isFeatured: false,
    price: 50,
    description: 'jar-of-activated-charcoal-facemask',
  },
  {
    id: 40,
    name: 'Leaf-socks',
    slug: 'legs-crossed-hemp-leaf-socks',
    category: 'Socks',
    image: 'legs-crossed-hemp-leaf-socks.jpg',
    isFeatured: false,
    price: 50,
    description: 'legs-crossed-hemp-leaf-socks',
  },

  {
    id: 41,
    name: 'Lemon-purse',
    slug: 'a-lemon-purse',
    category: 'Bag',
    image: 'lemon-purse.jpg',
    isFeatured: false,
    price: 50,
    description: 'lemon-purse',
  },
  {
    id: 42,
    name: 'A-light-brown-clutcht',
    slug: 'a-light-brown-clutch',
    category: 'Bag',
    image: 'light-brown-clutch.jpg',
    isFeatured: false,
    price: 50,
    description: 'light-brown-clutch',
  },

  {
    id: 43,
    name: 'A-light-pink-purse',
    slug: 'a-light-pink-purse',
    category: 'Bag',
    image: 'light-pink-purse.jpg',
    isFeatured: false,
    price: 50,
    description: 'light-pink-purse',
  },
  {
    id: 44,
    name: 'A-lime-green-fitness-tracker',
    slug: 'a-lime-green-fitness-tracker',
    category: 'Accessories',
    image: 'lime-green-fitness-tracker.jpg',
    isFeatured: false,
    price: 50,
    description: 'lime-green-fitness-tracker',
  },
  {
    id: 45,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 46,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 47,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 48,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 49,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 50,
    name: 'A-light-pink-purse',
    slug: 'a-light-pink-purse',
    category: 'Bag',
    image: 'light-pink-purse.jpg',
    isFeatured: false,
    price: 50,
    description: 'light-pink-purse',
  },
  {
    id: 51,
    name: 'A-lime-green-fitness-tracker',
    slug: 'a-lime-green-fitness-tracker',
    category: 'Accessories',
    image: 'lime-green-fitness-tracker.jpg',
    isFeatured: false,
    price: 50,
    description: 'lime-green-fitness-tracker',
  },
  {
    id: 52,
    name: 'Bamboo-wristwatch',
    slug: 'modern-bamboo-wristwatch',
    category: 'Watch',
    image: 'modern-bamboo-wristwatch.jpg',
    isFeatured: true,
    price: 50,
    description: 'modern-bamboo-wristwatch',
  },
  {
    id: 53,
    name: 'marble-fashion-wristwatch',
    slug: 'marble-fashion-wristwatch',
    category: 'Watch',
    image: 'marble-fashion-wristwatch.jpg',
    isFeatured: false,
    price: 50,
    description: 'marble-fashion-wristwatch',
  },
  {
    id: 54,
    name: 'Necklace-detail',
    slug: 'necklace-detail',
    category: 'Cosmetics',
    image: 'necklace-detail.jpg',
    isFeatured: false,
    price: 50,
    description: 'necklace-detail',
  },
  {
    id: 55,
    name: 'Headphone',
    slug: 'noise-cancelling-headphones',
    category: 'Accessories',
    image: 'noise-cancelling-headphones.jpg',
    isFeatured: true,
    price: 50,
    description: 'noise-cancelling-headphones',
  },
  {
    id: 56,
    name: 'Blue-skate-shoes',
    slug: 'pair-of-navy-blue-skate-shoes',
    category: 'Shoes',
    image: 'pair-of-navy-blue-skate-shoes.jpg',
    isFeatured: false,
    price: 50,
    description: 'pair-of-navy-blue-skate-shoes',
  },
  {
    id: 57,
    name: 'Purple-t-shirt',
    slug: 'purple-t-shirt',
    category: 'Shirts',
    image: 'purple-t-shirt.jpg',
    isFeatured: false,
    price: 50,
    description: 'purple-t-shirt',
  },
  {
    id: 58,
    name: 'Red-LED-shoes',
    slug: 'red-LED-shoes',
    category: 'Shoes',
    image: 'red-LED-shoes.jpg',
    isFeatured: false,
    price: 50,
    description: 'Red-LED-shoes',
  },
  {
    id: 59,
    name: 'Red-t-shirt',
    slug: 'red-t-shirt',
    category: 'Shirts',
    image: 'red-t-shirt.jpg',
    isFeatured: false,
    price: 50,
    description: 'red-t-shirt',
  },
  {
    id: 60,
    name: 'Black-sneaker',
    slug: 'right-foot-all-black-sneaker',
    category: 'Shoes',
    image: 'right-foot-all-black-sneaker.jpg',
    isFeatured: true,
    price: 50,
    description: 'right-foot-all-black-sneaker',
  },
  {
    id: 61,
    name: 'A-teal-t-shirt',
    slug: 'teal-t-shirt',
    category: 'Shirts',
    image: 'teal-t-shirt.jpg',
    isFeatured: false,
    price: 50,
    description: 'teal-t-shirt',
  },
];
