import '../styles/tailwind.css';
import type { AppProps } from 'next/app';
import Footer from '../components/Footer/Footer';
import { Provider as NextAuthProvider } from 'next-auth/client';
import { Provider as ReduxProvider } from 'react-redux';
import store from './../utils/store/store';
import Nav from '../components/Home/Nav';
import React from 'react';
import { CookiesProvider } from 'react-cookie';
import Head from 'next/head';
import { SnackbarProvider } from 'notistack';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <CookiesProvider>
      <ReduxProvider store={store}>
        <NextAuthProvider>
          <SnackbarProvider
            dense={true}
            anchorOrigin={{
              vertical: 'top',
              horizontal: 'center',
            }}
            iconVariant={{
              error: '✖️',
              warning: '⚠️',
              info: 'ℹ️',
            }}
          >
            {' '}
            <div className=''>
              <Head>
                <title>E-Commerce Website</title>
                <meta
                  name='description'
                  content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
              </Head>
              <Nav />
              <Component {...pageProps} />
              <Footer />
            </div>
          </SnackbarProvider>{' '}
        </NextAuthProvider>
      </ReduxProvider>
    </CookiesProvider>
  );
}

export default MyApp;
