import '../styles/tailwind.css';
import type { AppProps } from 'next/app';
import Footer from '../components/Footer/Footer';
import { Provider } from 'react-redux';
import store from './../utils/store/store';
import Nav from '../components/Home/Nav';
import React from 'react';
import { CookiesProvider } from 'react-cookie';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <CookiesProvider>
      <Provider store={store}>
        <div className=''>
        <Head>
        <title>E-Commerce Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
          <Nav />
          <Component {...pageProps} />
          <Footer />
        </div>
      </Provider>
    </CookiesProvider>
  );
}

export default MyApp;
